import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Header from "@/components/header";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import { Toaster } from "sonner";
import Footer from "@/components/footer";


const inter = Inter({subsets: ["latin"]});

export const metadata = {
  title: "SkillSync - AI Career Guide",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className}`}>
        <ClerkProvider appearance={{ baseTheme: dark }}>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            {/*Header */}
            <Header />

            <main className="min-h-screen">
             {children}
             <Toaster richColors/>
            </main>

            {/*Footer */}
            {/* <footer className="bg-muted/50 py-10">
              <div className="container mx-auto px-4 text-center text-gray-200">
                <p>Made by Ashwin.All right Reverserved</p>
              </div>
            </footer> */}
            <Footer />
          </ThemeProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
